# Generated by Django 3.1.3 on 2021-05-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='create_Date',
            new_name='create_date',
        ),
    ]
